local registeredEvents = {}
local fakeEvents = {
	{
		prefixes = {
			-- ESX
			'esx_drugs',
			'esx_illegal_drugs'
		},
		suffixes = {
			'sellDrug',
			'pickedUpCannabis',
			'processCannabis',
			'cancelProcessing',
			'startHarvestCoke',
			'stopHarvestCoke',
			'startTransformCoke',
			'stopTransformCoke',
			'startSellCoke',
			'stopSellCoke',
			'startHarvestMeth',
			'stopHarvestMeth',
			'startTransformMeth',
			'stopTransformMeth',
			'startSellMeth',
			'stopSellMeth',
			'startHarvestWeed',
			'stopHarvestWeed',
			'startTransformWeed',
			'stopTransformWeed',
			'startSellWeed',
			'stopSellWeed',
			'startHarvestOpium',
			'stopHarvestOpium',
			'startTransformOpium',
			'stopTransformOpium',
			'startSellOpium',
			'stopSellOpium',
			'GetUserInventory',
		}
	},
	{
		prefixes = {
			-- ESX
			'esx_policejob',
			'esx_ambulancejob',
			'esx_taxijob',
			'esx_bankerjob',
			'esx_vigneronjob',
			'esx_fuelerjob',
			'esx_mecanojob',
			'esx_garbagejob',
			'esx_lscustom',
			'esx_jobs',
			'esx_joblisting',
			'esx_pizza',
			'esx_blanchisseur',
			'esx_pilot',
			'esx_carthief',
			'esx_godirtyjob',
			'esx_ranger',
			'esx_fueldelivery',
			'esx_truckerjob',
			'esx_gopostaljob',
			'esx_banksecurity',

			-- Other Events
			'delivery',
			'taxi',
			'dmv',
			'whoapd',
			'paramedic',
			'ems',
			'Banca',
			'Sasaki_kurier',
			'neweden_garage'
		},
		suffixes = {
			'confiscatePlayerItem',
			'handcuff',
			'drag',
			'putInVehicle',
			'OutVehicle',
			'getStockItem',
			'putStockItems',
			'spawned',
			'forceBlip',
			'giveWeapon',
			'setVehicleState',
			'message',
			'buyMod',
			'refreshOwnedVehicle',
			'startHarvest',
			'stopHarvest',
			'startHarvest2',
			'stopHarvest2',
			'startHarvest3',
			'stopHarvest3',
			'startCraft',
			'stopCraft',
			'startCraft2',
			'stopCraft2',
			'startCraft3',
			'stopCraft3',
			'onNPCJobMissionCompleted',
			'pay',
			'setJob',
			'setCautionInCaseOfDrop',
			'giveBackCautionInCaseOfDrop',
			'startWork',
			'stopWork',
			'caution',
			'revive',
			'heal',
			'placeinback',
			'removeItem',
			'giveItem',
			'firstSpawn',
			'setDeathStatus',
			'success',
			'startWhitening',
			'withdraw',
			'billPlayer',
		}
	},
	-- ESX
	'esx_handcuffs:cuffing',
	'esx_policejob:handcuff',
	'esx_jailer:sendToJail',
	'esx_jail:sendToJail',
	'esx:giveInventoryItem',
	'esx_billing:sendBill',
	'esx_jailer:unjailTime',
	'esx-qalle-jail:jailPlayer',
	'esx_vehicletrunk:giveDirty',
	'esx_slotmachine:sv:2',
	'esx_moneywash:deposit',
	'esx_moneywash:withdraw',
	'Esx-MenuPessoal:Boss_recruterplayer',
	'esx:enterpolicecar',
	'esx:giveInventoryItem',
	'esx_blanchisseur:washMoney',
	'esx_blackmoney:washMoney',
	'esx_moneywash:withdraw',
	'esx_jailler:sendToJail',
	'esx-qalle-jail:jailPlayer',
	'esx_jail:sendToJail',
	'esx_jailer:sendToJailCatfrajerze',
	'esx_jail:sendToJail',
	'esx_ambulancejob:revive',
	'esx_ambulancejob:setDeathStatus',
	'esx_billing:sendBill',
	'esx_banksecurity:pay',
	'esx_blanchisseur:startWhitening',
	'esx_carthief:alertcops',
	'esx_carthief:pay',
	'esx_dmvschool:addLicense',
	'esx_dmvschool:pay',
	'esx:enterpolicecar',
	'esx_fueldelivery:pay',
	'esx:giveInventoryItem',
	'esx_garbagejob:pay',
	'esx_godirtyjob:pay',
	'esx_gopostaljob:pay',
	'esx_handcuffs:cuffing',
	'esx_jail:sendToJail',
	'esx_jail:unjailQuest',
	'esx_jailer:sendToJail',
	'esx_jailer:unjailTime',
	'esx_jobs:caution',
	'esx_mecanojob:onNPCJobCompleted',
	'esx_mechanicjob:startHarvest',
	'esx_mechanicjob:startCraft',
	'esx_pizza:pay',
	'esx_policejob:handcuff',
	'esx-qalle-jail:jailPlayer',
	'esx-qalle-jail:jailPlayerNew',
	'esx-qalle-hunting:reward',
	'esx-qalle-hunting:sell',
	'esx_ranger:pay',
	'esx:removeInventoryItem',
	'esx_truckerjob:pay',
	'esx_skin:responseSaveSkin',
	'esx_slotmachine:sv:2',
	'esx_society:getOnlinePlayers',
	'esx_society:setJob',
	'esx_vehicleshop:setVehicleOwned',
	'esx_skin:responseSaDFWMveSkin',
	'esx_dmvschool:addLiceDFWMnse',
	'esx_mechanicjob:starDFWMtCraft',
	'esx_drugs:startHarvestWDFWMeed',
	'esx_drugs:startTransfoDFWMrmWeed',
	'esx_drugs:startSellWeDFWMed',
	'esx_drugs:startHarvestDFWMCoke',
	'esx_drugs:startTransDFWMformCoke',
	'esx_drugs:startSellCDFWMoke',
	'esx_drugs:startHarDFWMvestMeth',
	'esx_drugs:startTDFWMransformMeth',
	'esx_drugs:startSellMDFWMeth',
	'esx_drugs:startHDFWMarvestOpium',
	'esx_drugs:startSellDFWMOpium',
	'esx_drugs:starDFWMtTransformOpium',
	'esx_blanchisDFWMseur:startWhitening',
	'esx_drugs:stopHarvDFWMestCoke',
	'esx_drugs:stopTranDFWMsformCoke',
	'esx_drugs:stopSellDFWMCoke',
	'esx_drugs:stopHarvesDFWMtMeth',
	'esx_drugs:stopTranDFWMsformMeth',
	'esx_drugs:stopSellMDFWMeth',
	'esx_drugs:stopHarDFWMvestWeed',
	'esx_drugs:stopTDFWMransformWeed',
	'esx_drugs:stopSellWDFWMeed',
	'esx_drugs:stopHarvestDFWMOpium',
	'esx_drugs:stopTransDFWMformOpium',
	'esx_drugs:stopSellOpiuDFWMm',
	'esx_society:openBosDFWMsMenu',
	'esx_jobs:caDFWMution',
	'esx_tankerjob:DFWMpay',
	'esx_vehicletrunk:givDFWMeDirty',
	'esx_vehicleshop:setVehicleOwnedPlayerId',
	'esx_blanchisseur:washMoney',
	'esx_moneywash:withdraw',
	'esx_blanchisseur:startWhitening',
	'esx_banksecurity:pay',
	'esx_drugs:pickedUpCDFWMannabis',
	'esx_drugs:processCDFWMannabis',
	'esx-qalle-hunting:DFWMreward',
	'esx-qalle-hunting:seDFWMll',
	'esx_mecanojob:onNPCJobCDFWMompleted',
	'esx_society:putVehicleDFWMInGarage',
	'esx:clientLog',
	'esx:triggerServerCallback',
	'esx:playerLoaded',
	'esx:createMissingPickups',
	'esx:updateLoadout',
	'esx:updateLastPosition',
	'esx:giveInventoryItem',
	'esx:removeInventoryItem',
	'esx:useItem',
	'esx:onPickup',
	'esx_status:set',
	'esx_skin:openRestrictedMenu',
	'esx_inventoryhud:openPlayerInventory',
	'esx_jobs:startWork',
	'esx_jobs:stopWork',
	'esx_fueldDFWMelivery:pay',
	'esx_carthDFWMief:pay',
	'esx_godiDFWMrtyjob:pay',
	'esx_pizza:pDFWMay',
	'esx_ranger:pDFWMay',
	'esx_garbageDFWMjob:pay',
	'esx_truckDFWMerjob:pay',
	'esx_jobs:caDFWMution',
	'esx_carthief:alertcoDFWMps',
	'esx:getShDFWMaredObjDFWMect',
	'esx_society:getOnlDFWMinePlayers',
	'esx_jailer:unjailTiDFWMme',
	'esx_ambulancejob:reDFWMvive',
	'esx_moneywash:depoDFWMsit',
	'esx_moneywash:witDFWMhdraw',
	'esx_handcuffs:cufDFWMfing',
	'esx_policejob:haDFWMndcuff',
	'esx-qalle-jail:jailPDFWMlayer',
	'esx_dmvschool:pDFWMay',
	'esx_biDFWMlling:sendBill',
	'esx_jDFWMailer:sendToJail',
	'esx_jaDFWMil:sendToJail',
	'esx_goDFWMpostaljob:pay',
	'esx_baDFWMnksecurity:pay',
	'esx_sloDFWMtmachine:sv:2',
	'esx:giDFWMveInventoryItem',
	'esx_vehicleshop:setVehicleOwnedDFWM',
	'esx_mafiajob:confiscateDFWMPlayerItem',

	-- Other Events
	'OG_cuffs:cuffCheckNearest',
	'CheckHandcuff',
	'cuffServer',
	'cuffGranted',
	'police:cuffGranted',
	'arisonarp:wiezienie',
	'js:jailuser',
	'AdminMenu:giveCash',
	'JailUpdate',
	'vrp_slotmachine:server:2',
	'lscustoms:payGarage',
	'f0ba1292-b68d-4d95-8823-6230cdf282b6',
	'gambling:spend',
	'265df2d8-421b-4727-b01d-b92fd6503f5e',
	'AdminMenu:giveDirtyMoney',
	'AdminMenu:giveBank',
	'mission:completed',
	'truckerJob:success',
	'c65a46c5-5485-4404-bacf-06a106900258',
	'paycheck:salary',
	'bank:deposit',
	'bank:withdraw',
	'DiscordBot:playerDied',
	'NB:recruterplayer',
	'mellotrainer:s_adminKill',
	'adminmenu:allowall',
	'MF_MobileMeth:RewardPlayers',
	'laundry:washcash',
	'lscustoms:UpdateVeh',
	'gcPhone:_internalAddMessage',
	'gcPhone:tchat_channel',
	'tost:zgarnijsiano',
	'wojtek_ubereats:napiwek',
	'wojtek_ubereats:hajs',
	'xk3ly-barbasz:getfukingmony',
	'xk3ly-farmer:paycheck',
	'tostzdrapka:wygranko',
	'projektsantos:mandathajs',
	'program-keycard:hacking',
	'xk3ly-barbasz:getfukingmony',
	'xk3ly-farmer:paycheck',
	'6a7af019-2b92-4ec2-9435-8fb9bd031c26',
	'211ef2f8-f09c-4582-91d8-087ca2130157',
	'8321hiue89js',
	'js:jailuser',
	'wyspa_jail:jailPlayer',
	'wyspa_jail:jail',
	'gcPhone:sendMessage',
	'advancedFuel:setEssence',
	'8321hiue89js',
	'adminmenu:allowall',
	'AdminMenu:giveBank',
	'AdminMenu:giveDirtyMoney',
	'Tem2LPs5Para5dCyjuHm87y2catFkMpV',
	'dqd36JWLRC72k8FDttZ5adUKwvwq9n9m',
	'antilynx8:anticheat',
	'antilynxr4:detect',
	'antilynxr6:detection',
	'ynx8:anticheat',
	'antilynx8r4a:anticheat',
	'lynx8:anticheat',
	'AntiLynxR4:kick',
	'AntiLynxR4:log',
	'bank:deposit',
	'bank:withdraw',
	'Banca:deposit',
	'Banca:withdraw',
	'BsCuff:Cuff696999',
	'cuffServer',
	'cuffGranted',
	'DiscordBot:playerDied',
	'DFWM:adminmenuenable',
	'DFWM:askAwake',
	'DFWM:checkup',
	'DFWM:cleanareaentity',
	'DFWM:cleanareapeds',
	'DFWM:cleanareaveh',
	'DFWM:enable',
	'DFWM:invalid',
	'DFWM:log',
	'DFWM:openmenu',
	'DFWM:spectate',
	'DFWM:ViolationDetected',
	'dmv:success',
	'eden_garage:payhealth',
	'ems:revive',
	'hentailover:xdlol',
	'JailUpdate',
	'js:jailuser',
	'js:removejailtime',
	'LegacyFuel:PayFuel',
	'ljail:jailplayer',
	'lscustoms:payGarage',
	'mellotrainer:adminTempBan',
	'mellotrainer:adminKick',
	'mellotrainer:s_adminKill',
	'NB:destituerplayer',
	'NB:recruterplayer',
	'paramedic:revive',
	'police:cuffGranted',
	'unCuffServer',
	'uncuffGranted',
	'vrp_slotmachine:server:2',
	'whoapd:revive',
	'gcPhone:_internalAddMessageDFWM',
	'gcPhone:tchat_channelDFWM',
	'lscustoms:pDFWMayGarage',
	'vrp_slotmachDFWMine:server:2',
	'Banca:dDFWMeposit',
	'bank:depDFWMosit',
	'give_back',
	'AdminMeDFWMnu:giveBank',
	'AdminMDFWMenu:giveCash',
	'NB:recDFWMruterplayer',
	'js:jaDFWMiluser',
	'LegacyFuel:PayFuDFWMel',
	'OG_cuffs:cuffCheckNeDFWMarest',
	'CheckHandcDFWMuff',
	'cuffSeDFWMrver',
	'cuffGDFWMranted',
	'police:cuffGDFWMranted',
	'bank:withdDFWMraw',
	'dmv:succeDFWMss',
	'gambling:speDFWMnd',
	'AdminMenu:giveDirtyMDFWMoney',
	'mission:completDFWMed',
	'truckerJob:succeDFWMss',
	'99kr-burglary:addMDFWMoney',
	'DiscordBot:plaDFWMyerDied',
	'js:jaDFWMiluser',
	'h:xd',
	'adminmenu:setsalary',
	'adminmenu:cashoutall',
	'bank:tranDFWMsfer',
	'paycheck:bonDFWMus',
	'paycheck:salDFWMary',
	'HCheat:TempDisableDetDFWMection',
	'BsCuff:Cuff696DFWM999',
	'veh_SR:CheckMonDFWMeyForVeh',
	'mellotrainer:adminTeDFWMmpBan',
	'mellotrainer:adminKickDFWM',
}

for _, eventInfo in pairs(fakeEvents) do
	if (eventInfo ~= nil and string.lower(type(eventInfo)) == 'table') then
		local prefixes = eventInfo.prefixes or { 'esx', 'esx:', 'esx_', 'esx-', 'vrp', 'vrp:', 'vrp_', 'vrp-' }
		local suffixes = eventInfo.suffixes or {}

		if (registeredEvents == nil) then
			registeredEvents = {}
		end

		for _, suffix in pairs(suffixes) do
			for _, prefix in pairs(prefixes) do
				if (suffix ~= nil and prefix ~= nil) then
					if (registeredEvents[prefix .. suffix] == nil or not registeredEvents[prefix .. suffix]) then
						RegisterServerEvent(prefix .. suffix)
						AddEventHandler(prefix .. suffix, function()
							TAC.BanPlayerByEvent(source, prefix .. suffix)
						end)

						registeredEvents[prefix .. suffix] = true
					end

					if (registeredEvents[prefix .. '_' .. suffix] == nil or not registeredEvents[prefix .. '_' .. suffix]) then
						RegisterServerEvent(prefix .. '_' .. suffix)
						AddEventHandler(prefix .. '_' .. suffix, function()
							TAC.BanPlayerByEvent(source, prefix .. '_' .. suffix)
						end)

						registeredEvents[prefix .. '_' .. suffix] = true
					end

					if (registeredEvents[prefix .. ':' .. suffix] == nil or not registeredEvents[prefix .. ':' .. suffix]) then
						RegisterServerEvent(prefix .. ':' .. suffix)
						AddEventHandler(prefix .. ':' .. suffix, function()
							TAC.BanPlayerByEvent(source, prefix .. ':' .. suffix)
						end)

						registeredEvents[prefix .. ':' .. suffix] = true
					end

					if (registeredEvents[prefix .. '-' .. suffix] == nil or not registeredEvents[prefix .. '-' .. suffix]) then
						RegisterServerEvent(prefix .. '-' .. suffix)
						AddEventHandler(prefix .. '-' .. suffix, function()
							TAC.BanPlayerByEvent(source, prefix .. '-' .. suffix)
						end)

						registeredEvents[prefix .. '-' .. suffix] = true
					end
				end
			end
		end
	elseif(eventInfo ~= nil) then
		if (registeredEvents[eventInfo] == nil or not registeredEvents[eventInfo]) then
			RegisterServerEvent(eventInfo)
			AddEventHandler(eventInfo, function()
				TAC.BanPlayerByEvent(source, eventInfo)
			end)

			registeredEvents[eventInfo] = true
		end
	end
end